#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_m42_sdf_physics = env_modules.Clone()

# Generate shader header from .glsl file
env_m42_sdf_physics.GLSL_HEADER("shaders/sdf_raymarch_inc.glsl")
env_m42_sdf_physics.Depends(Glob("shaders/*.glsl.gen.h"), ["shaders/sdf_raymarch_inc.glsl", "#glsl_builders.py"])

# Add module source files (material system)
env_m42_sdf_physics.add_source_files(env.modules_sources, "*.cpp")

# Add SDF rendering nodes (subdirectory)
env_m42_sdf_physics.add_source_files(env.modules_sources, "nodes/*.cpp")
